[package]
name = "erislight"
version = "111.111.111"
edition = "2021"
license = "MIT"
repository = "https://github.com/MortemTeam/erislight"

[lib]
crate-type = ["cdylib"]

[dependencies]
auxtools = {git = "https://github.com/willox/auxtools"}
