[package]
name = "erislight"
version = "666.3.4-rc1"
edition = "2021"
license = "MIT"
repository = "https://github.com/MortemTeam/erislight"

[profile.release]
lto = true

[lib]
crate-type = ["cdylib"]

[dependencies]
auxtools = {git = "https://github.com/willox/auxtools"}
array_tool = "1.0.3"
